/**
 * Initial Seed & Mock Data
 * Dies Natalis UMS 2026 Minisoccer Tournament (16-Team Knockout System)
 */

export const INITIAL_TEAMS = [
  { id: 'team-1', name: 'Teknik FC (FT UMS)', facultyUnit: 'Fakultas Teknik', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FTUMS&backgroundColor=003366', managerName: 'Ir. Ahmad Subagyo', managerPhone: '081234567890', status: 'APPROVED' },
  { id: 'team-2', name: 'Ekonomi Squad (FEB UMS)', facultyUnit: 'Fakultas Ekonomi & Bisnis', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FEBUMS&backgroundColor=006699', managerName: 'Dr. Endang Rahayu', managerPhone: '081298765432', status: 'APPROVED' },
  { id: 'team-3', name: 'Kedokteran FC (FK UMS)', facultyUnit: 'Fakultas Kedokteran', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKUMS&backgroundColor=009966', managerName: 'dr. Rizky Kurniawan', managerPhone: '081311223344', status: 'APPROVED' },
  { id: 'team-4', name: 'Hukum United (FH UMS)', facultyUnit: 'Fakultas Hukum', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FHUMS&backgroundColor=990033', managerName: 'Prof. Bambang Setiawan', managerPhone: '081355667788', status: 'APPROVED' },
  { id: 'team-5', name: 'FIK Warriors (FIK UMS)', facultyUnit: 'Fakultas Ilmu Kesehatan', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FIKUMS&backgroundColor=ff6600', managerName: 'Nrs. Tri Astuti', managerPhone: '081788990011', status: 'APPROVED' },
  { id: 'team-6', name: 'FKIP All Star (FKIP UMS)', facultyUnit: 'Keguruan & Ilmu Pendidikan', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKIPUMS&backgroundColor=cc0099', managerName: 'Drs. Wahyu Hidayat', managerPhone: '081822334455', status: 'APPROVED' },
  { id: 'team-7', name: 'Farmasi Knights (FF UMS)', facultyUnit: 'Fakultas Farmasi', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FFUMS&backgroundColor=00cc99', managerName: 'apt. Fitriani', managerPhone: '081933445566', status: 'APPROVED' },
  { id: 'team-8', name: 'Rektorat Star (Unit Rektorat)', facultyUnit: 'Unit Rektorat & Staf UMS', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=REKTORAT&backgroundColor=6600cc', managerName: 'Drs. Sugeng Mulyono', managerPhone: '081244556677', status: 'APPROVED' },
  { id: 'team-9', name: 'FKI Cyber FC (FKI UMS)', facultyUnit: 'Komunikasi & Informatika', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKIUMS&backgroundColor=0099cc', managerName: 'Husni Thamrin, Ph.D.', managerPhone: '081233445566', status: 'APPROVED' },
  { id: 'team-10', name: 'Psikologi FC (FPsi UMS)', facultyUnit: 'Fakultas Psikologi', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FPSIUMS&backgroundColor=ff3399', managerName: 'Dr. Wisnu Sri', managerPhone: '081344556677', status: 'APPROVED' },
  { id: 'team-11', name: 'Geografi Earth (FG UMS)', facultyUnit: 'Fakultas Geografi', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FGUMS&backgroundColor=669900', managerName: 'Dr. Choiroel Anam', managerPhone: '081455667788', status: 'APPROVED' },
  { id: 'team-12', name: 'FAI Horizon (FAI UMS)', facultyUnit: 'Fakultas Agama Islam', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FAIUMS&backgroundColor=009933', managerName: 'Dr. Syamsul Hidayat', managerPhone: '081566778899', status: 'APPROVED' },
  { id: 'team-13', name: 'Pascasarjana Elite (S2 UMS)', facultyUnit: 'Sekolah Pascasarjana', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=S2UMS&backgroundColor=993300', managerName: 'Prof. Anam Sutopo', managerPhone: '081677889900', status: 'APPROVED' },
  { id: 'team-14', name: 'Pertanian FC (FP UMS)', facultyUnit: 'Fakultas Pertanian', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FPUMS&backgroundColor=336600', managerName: 'Dr. Samingun', managerPhone: '081788990022', status: 'APPROVED' },
  { id: 'team-15', name: 'Kedokteran Gigi (FKG UMS)', facultyUnit: 'Fakultas Kedokteran Gigi', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKGUMS&backgroundColor=006666', managerName: 'drg. Dwi Linna', managerPhone: '081899001122', status: 'APPROVED' },
  { id: 'team-16', name: 'RSGM Medical (Unit RSGM)', facultyUnit: 'Unit RSGM UMS', logoUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=RSGMUMS&backgroundColor=cc0033', managerName: 'Dr. drg. Noor Hafida', managerPhone: '081900112233', status: 'APPROVED' }
];

export const INITIAL_PLAYERS = [
  { id: 'p-1', teamId: 'team-1', fullName: 'Dimas Anggara', identityNumber: 'D100220101', position: 'GOALKEEPER', jerseyNumber: 1, photoProfileUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-2', teamId: 'team-1', fullName: 'Farhan Putra', identityNumber: 'D100220105', position: 'DEFENDER', jerseyNumber: 4, photoProfileUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-3', teamId: 'team-1', fullName: 'Reza Pratama', identityNumber: 'D100220112', position: 'MIDFIELDER', jerseyNumber: 8, photoProfileUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-4', teamId: 'team-1', fullName: 'Bagus Kahfi', identityNumber: 'D100220120', position: 'FORWARD', jerseyNumber: 9, photoProfileUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-5', teamId: 'team-1', fullName: 'Alfi Syahrin', identityNumber: 'D100220130', position: 'FORWARD', jerseyNumber: 10, photoProfileUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200' },
  
  { id: 'p-6', teamId: 'team-2', fullName: 'Bayu Saputra', identityNumber: 'B100220050', position: 'GOALKEEPER', jerseyNumber: 12, photoProfileUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-7', teamId: 'team-2', fullName: 'Faris Ramadhan', identityNumber: 'B100220058', position: 'DEFENDER', jerseyNumber: 3, photoProfileUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-8', teamId: 'team-2', fullName: 'Hendra Setiawan', identityNumber: 'B100220072', position: 'MIDFIELDER', jerseyNumber: 7, photoProfileUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-9', teamId: 'team-2', fullName: 'Gilang Dirga', identityNumber: 'B100220090', position: 'FORWARD', jerseyNumber: 11, photoProfileUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200' },

  { id: 'p-10', teamId: 'team-3', fullName: 'dr. Kevin Sanjaya', identityNumber: 'J500210015', position: 'MIDFIELDER', jerseyNumber: 10, photoProfileUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-11', teamId: 'team-3', fullName: 'dr. Marcus Gideon', identityNumber: 'J500210022', position: 'DEFENDER', jerseyNumber: 5, photoProfileUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200' },
  { id: 'p-12', teamId: 'team-5', fullName: 'Taufik Hidayat', identityNumber: 'J410220010', position: 'FORWARD', jerseyNumber: 9, photoProfileUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200' }
];

export const INITIAL_OFFICIALS = [
  { id: 'off-1', teamId: 'team-1', fullName: 'Coach Bambang Nurdiansyah', identityNumber: '0012057201', role: 'HEAD_COACH' },
  { id: 'off-2', teamId: 'team-1', fullName: 'Dr. Aris Triyono', identityNumber: '0014088002', role: 'OFFICIAL' },
  { id: 'off-3', teamId: 'team-2', fullName: 'Coach Rahmad Darmawan', identityNumber: '0018116503', role: 'HEAD_COACH' }
];

// Initial 16-Team Knockout Matches
export const INITIAL_MATCHES = [
  // Round of 16 (Match 1 - 8)
  { id: 'm-1', matchNumber: 1, stage: 'ROUND_OF_16', homeTeamId: 'team-1', homeTeamName: 'Teknik FC (FT UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FTUMS&backgroundColor=003366', awayTeamId: 'team-2', awayTeamName: 'Ekonomi Squad (FEB UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FEBUMS&backgroundColor=006699', homeScore: 3, awayScore: 1, pitchLocation: 'Lapangan A UMS Stadium', status: 'FINISHED', events: [{ id: 'ev-1', minute: 12, eventType: 'GOAL', teamId: 'team-1', playerId: 'p-4', playerFullName: 'Bagus Kahfi' }, { id: 'ev-2', minute: 34, eventType: 'GOAL', teamId: 'team-2', playerId: 'p-9', playerFullName: 'Gilang Dirga' }, { id: 'ev-3', minute: 48, eventType: 'GOAL', teamId: 'team-1', playerId: 'p-5', playerFullName: 'Alfi Syahrin' }] },
  { id: 'm-2', matchNumber: 2, stage: 'ROUND_OF_16', homeTeamId: 'team-3', homeTeamName: 'Kedokteran FC (FK UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKUMS&backgroundColor=009966', awayTeamId: 'team-4', awayTeamName: 'Hukum United (FH UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FHUMS&backgroundColor=990033', homeScore: 2, awayScore: 0, pitchLocation: 'Lapangan B UMS Stadium', status: 'FINISHED', events: [{ id: 'ev-4', minute: 15, eventType: 'GOAL', teamId: 'team-3', playerId: 'p-10', playerFullName: 'dr. Kevin Sanjaya' }] },
  { id: 'm-3', matchNumber: 3, stage: 'ROUND_OF_16', homeTeamId: 'team-5', homeTeamName: 'FIK Warriors (FIK UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FIKUMS&backgroundColor=ff6600', awayTeamId: 'team-6', awayTeamName: 'FKIP All Star (FKIP UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKIPUMS&backgroundColor=cc0099', homeScore: 2, awayScore: 1, pitchLocation: 'Lapangan A UMS Stadium', status: 'FINISHED', events: [{ id: 'ev-5', minute: 22, eventType: 'GOAL', teamId: 'team-5', playerId: 'p-12', playerFullName: 'Taufik Hidayat' }] },
  { id: 'm-4', matchNumber: 4, stage: 'ROUND_OF_16', homeTeamId: 'team-7', homeTeamName: 'Farmasi Knights (FF UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FFUMS&backgroundColor=00cc99', awayTeamId: 'team-8', awayTeamName: 'Rektorat Star (Unit Rektorat)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=REKTORAT&backgroundColor=6600cc', homeScore: 1, awayScore: 0, pitchLocation: 'Lapangan B UMS Stadium', status: 'FINISHED', events: [] },
  { id: 'm-5', matchNumber: 5, stage: 'ROUND_OF_16', homeTeamId: 'team-9', homeTeamName: 'FKI Cyber FC (FKI UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKIUMS&backgroundColor=0099cc', awayTeamId: 'team-10', awayTeamName: 'Psikologi FC (FPsi UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FPSIUMS&backgroundColor=ff3399', homeScore: 3, awayScore: 2, pitchLocation: 'Lapangan A UMS Stadium', status: 'FINISHED', events: [] },
  { id: 'm-6', matchNumber: 6, stage: 'ROUND_OF_16', homeTeamId: 'team-11', homeTeamName: 'Geografi Earth (FG UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FGUMS&backgroundColor=669900', awayTeamId: 'team-12', awayTeamName: 'FAI Horizon (FAI UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FAIUMS&backgroundColor=009933', homeScore: 0, awayScore: 1, pitchLocation: 'Lapangan B UMS Stadium', status: 'FINISHED', events: [] },
  { id: 'm-7', matchNumber: 7, stage: 'ROUND_OF_16', homeTeamId: 'team-13', homeTeamName: 'Pascasarjana Elite (S2 UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=S2UMS&backgroundColor=993300', awayTeamId: 'team-14', awayTeamName: 'Pertanian FC (FP UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FPUMS&backgroundColor=336600', homeScore: 2, awayScore: 0, pitchLocation: 'Lapangan A UMS Stadium', status: 'FINISHED', events: [] },
  { id: 'm-8', matchNumber: 8, stage: 'ROUND_OF_16', homeTeamId: 'team-15', homeTeamName: 'Kedokteran Gigi (FKG UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKGUMS&backgroundColor=006666', awayTeamId: 'team-16', awayTeamName: 'RSGM Medical (Unit RSGM)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=RSGMUMS&backgroundColor=cc0033', homeScore: 1, awayScore: 2, pitchLocation: 'Lapangan B UMS Stadium', status: 'FINISHED', events: [] },

  // Quarter-Finals (Match 9 - 12)
  { id: 'm-9', matchNumber: 9, stage: 'QUARTER_FINAL', homeTeamId: 'team-1', homeTeamName: 'Teknik FC (FT UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FTUMS&backgroundColor=003366', awayTeamId: 'team-3', awayTeamName: 'Kedokteran FC (FK UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKUMS&backgroundColor=009966', homeScore: 2, awayScore: 1, pitchLocation: 'Lapangan A UMS Stadium', status: 'FINISHED', events: [] },
  { id: 'm-10', matchNumber: 10, stage: 'QUARTER_FINAL', homeTeamId: 'team-5', homeTeamName: 'FIK Warriors (FIK UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FIKUMS&backgroundColor=ff6600', awayTeamId: 'team-7', awayTeamName: 'Farmasi Knights (FF UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FFUMS&backgroundColor=00cc99', homeScore: 3, awayScore: 0, pitchLocation: 'Lapangan B UMS Stadium', status: 'FINISHED', events: [] },
  { id: 'm-11', matchNumber: 11, stage: 'QUARTER_FINAL', homeTeamId: 'team-9', homeTeamName: 'FKI Cyber FC (FKI UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKIUMS&backgroundColor=0099cc', awayTeamId: 'team-12', awayTeamName: 'FAI Horizon (FAI UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FAIUMS&backgroundColor=009933', homeScore: 1, awayScore: 0, pitchLocation: 'Lapangan A UMS Stadium', status: 'FINISHED', events: [] },
  { id: 'm-12', matchNumber: 12, stage: 'QUARTER_FINAL', homeTeamId: 'team-13', homeTeamName: 'Pascasarjana Elite (S2 UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=S2UMS&backgroundColor=993300', awayTeamId: 'team-16', awayTeamName: 'RSGM Medical (Unit RSGM)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=RSGMUMS&backgroundColor=cc0033', homeScore: 0, awayScore: 2, pitchLocation: 'Lapangan B UMS Stadium', status: 'FINISHED', events: [] },

  // Semi-Finals (Match 13 - 14)
  { id: 'm-13', matchNumber: 13, stage: 'SEMI_FINAL', homeTeamId: 'team-1', homeTeamName: 'Teknik FC (FT UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FTUMS&backgroundColor=003366', awayTeamId: 'team-5', awayTeamName: 'FIK Warriors (FIK UMS)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FIKUMS&backgroundColor=ff6600', homeScore: 2, awayScore: 1, pitchLocation: 'Lapangan A UMS Stadium', status: 'LIVE', events: [{ id: 'ev-6', minute: 14, eventType: 'GOAL', teamId: 'team-1', playerId: 'p-4', playerFullName: 'Bagus Kahfi' }] },
  { id: 'm-14', matchNumber: 14, stage: 'SEMI_FINAL', homeTeamId: 'team-9', homeTeamName: 'FKI Cyber FC (FKI UMS)', homeTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=FKIUMS&backgroundColor=0099cc', awayTeamId: 'team-16', awayTeamName: 'RSGM Medical (Unit RSGM)', awayTeamLogo: 'https://api.dicebear.com/7.x/identicon/svg?seed=RSGMUMS&backgroundColor=cc0033', homeScore: 0, awayScore: 0, pitchLocation: 'Lapangan B UMS Stadium', status: 'SCHEDULED', events: [] },

  // 3rd Place Playoff (Match 15)
  { id: 'm-15', matchNumber: 15, stage: 'THIRD_PLACE', homeTeamId: null, homeTeamName: 'Kalah Semi Final 1', homeTeamLogo: '', awayTeamId: null, awayTeamName: 'Kalah Semi Final 2', awayTeamLogo: '', homeScore: 0, awayScore: 0, pitchLocation: 'Lapangan B UMS Stadium', status: 'SCHEDULED', events: [] },

  // Grand Final (Match 16)
  { id: 'm-16', matchNumber: 16, stage: 'FINAL', homeTeamId: null, homeTeamName: 'Pemenang Semi Final 1', homeTeamLogo: '', awayTeamId: null, awayTeamName: 'Pemenang Semi Final 2', awayTeamLogo: '', homeScore: 0, awayScore: 0, pitchLocation: 'Lapangan A UMS Stadium', status: 'SCHEDULED', events: [] }
];
